
//--- constants ---------------------

export const

// for row, and 1st column colors
NAMEOFDAYFULL = ["Sunday", "Monday", "Tuesday",
  "Wednesday", "Thursday", "Friday", "Saturday"
],
NAMEOFDAYTHAI = ["อาทิตย์", "จันทร์", "อังคาร", "พุธ", "พฤหัส", "ศุกร์", "เสาร์"],
THAIMONTH = ["มค.", "กพ.", "มีค.", "เมย.", "พค.", "มิย.", "กค.", "สค.", "กย.", "ตค.", "พย.", "ธค."],
THAIMONTHFULL = [ "มกราคม", "กุมภาพันธ์", "มีนาคม", "เมษายน", "พฤษภาคม", "มิถุนายน", 
                  "กรกฎาคม", "สิงหาคม", "กันยายน", "ตุลาคม", "พฤศจิกายน", "ธันวาคม" ],

// ["type", "width", "name", "label", "id"]
REGISTERSHEET = [
  ["spanInSpan", "70", "", "ห้อง ", "oproomequip"],
  ["spanInSpan", "70", "", "Case ", "casenumequip"],
  ["spanInSpan", "100", "", "เวลา ", "optimeequip"],
  ["spanInSpan", "", "", "วัน", "opdayequip"],
  ["spanInSpan", "120", "", "ที่ ", "opdatethequip"],
  ["spanInSpan", "", "", "Surgeon ", "staffnameequip"],
  ["br", "", "", "", ""],
  ["br", "", "", "", ""],
  ["span", "110", "", "ชื่อ-นามสกุล", ""],
  ["span", "", "", "", "patientnameequip"],
  ["span", "20", "", "", ""],
  ["span", "", "", "อายุ&nbsp;", ""],
  ["span", "", "", "", "ageequip"],
  ["span", "20", "", "", ""],
  ["span", "", "", "HN&nbsp;", ""],
  ["span", "", "", "", "hnequip"],
  ["br", "", "", "", ""],
  // floatleft makes the subsequent text rows go downwards
  // instead of pushing previous rows upward
  ["span", "110 floatleft", "", "Diagnosis", ""],
  ["span", "", "", "", "diagnosisequip"],
  ["br", "", "", "", ""],
  ["span", "110 floatleft", "", "Operation", ""],
  ["span", "", "", "", "treatmentequip"],
  ["br", "", "", "", ""],
  ["br", "", "", "", ""],
  ["divbegin", "", "copay", "", ""],
  ["span", "110", "", "", ""],
  ["span", "", "", "<i><b>***</b> ผู้ป่วยและญาติสามารถ<b><u>จ่ายส่วนเกินได้ </u></b></i> ", ""],
  ["text", "110 textcenter", "", "", ""],
  ["span", "", "", " บาท <b>***</b>", ""],
  ["divend", "", "", "", ""],
  ["br", "", "", "", ""],
  ["divbegin", "", "Position", "", ""],
  ["span", "110", "", "Position", ""],
  ["radio", "150", "pose", "Supine left", ""],
  ["radio", "150", "pose", "Supine right", ""],
  ["radio", "", "pose", "Supine", ""],
  ["br", "", "", "", ""],
  ["span", "110", "", "", ""],
  ["radio", "150", "pose", "Parkbench ขวาลง", ""],
  ["radio", "150", "pose", "Lateral ขวาลง", ""],
  ["radio", "", "pose", "Semiprone ขวาลง", ""],
  ["br", "", "", "", ""],
  ["span", "110", "", "", ""],
  ["radio", "150", "pose", "Parkbench ซ้ายลง", ""],
  ["radio", "150", "pose", "Lateral ซ้ายลง", ""],
  ["radio", "", "pose", "Semiprone ซ้ายลง", ""],
  ["br", "", "", "", ""],
  ["span", "110", "", "", ""],
  ["radio", "150", "pose", "Concorde", ""],
  ["radio", "150", "pose", "Prone", ""],
  ["br", "", "", "", ""],
  ["span", "110", "", "", ""],
  ["text", "400", "", "", ""],
  ["divend", "", "", "", ""],
  ["br", "", "", "", ""],
  ["br", "", "", "", ""],
  ["divbegin", "", "Imaging", "", ""],
  ["span", "110", "", "Imaging", ""],
  ["checkbox", "150", "", "Fluoroscope", ""],
  ["checkbox", "130", "", "O-arm", ""],
  ["checkbox", "", "", "Navigator frameless", ""],
  ["br", "", "", "", ""],
  ["span", "110", "", "", ""],
  ["checkbox", "150", "", "Robotics", ""],
  ["checkbox", "130", "", "iCT", ""],
  ["checkbox", "", "", "Navigator with frame", ""],
  ["br", "", "", "", ""],
  ["span", "110", "", "", ""],
  ["checkbox", "150", "", "iMRI", ""],
  ["checkbox", "", "", "Stereotactic frame-based", ""],
  ["br", "", "", "", ""],
  ["span", "110", "", "", ""],
  ["text", "400", "", "", ""],
  ["divend", "", "", "", ""],
  ["br", "", "", "", ""],
  ["br", "", "", "", ""],
  ["divbegin", "", "อุปกรณ์ยึดผู้ป่วย", "", ""],
  ["span", "110", "", "อุปกรณ์ยึดผู้ป่วย", ""],
  ["checkbox", "150", "", "Mayfield", ""],
  ["checkbox", "150", "", "Gel Head Ring", ""],
  ["checkbox", "", "", "Horseshoe", ""],
  ["br", "", "", "", ""],
  ["span", "110", "", "", ""],
  ["text", "400", "", "", ""],
  ["divend", "", "", "", ""],
  ["br", "", "", "", ""],
  ["br", "", "", "", ""],
  ["divbegin", "", "เครื่องตัดกระดูก", "", ""],
  ["span", "110", "", "เครื่องตัดกระดูก", ""],
  ["checkbox", "150", "", "High Speed Drill", ""],
  ["checkbox", "150", "", "Sagittal Saw", ""],
  ["checkbox", "", "", "Osteotome", ""],
  ["br", "", "", "", ""],
  ["span", "110", "", "", ""],
  ["text", "400", "", "", ""],
  ["divend", "", "", "", ""],
  ["br", "", "", "", ""],
  ["br", "", "", "", ""],
  ["divbegin", "", "กล้อง", "", ""],
  ["span", "110", "", "กล้อง", ""],
  ["radio", "150", "Microscope", "Microscope", ""],
  ["checkbox", "150", "", "ICG", ""],
  ["checkbox", "", "", "Endoscope", ""],
  ["br", "", "", "", ""],
  ["span", "110", "", "", ""],
  ["radio", "150", "Microscope", "Pentaro 900", ""],
  ["br", "", "", "", ""],
  ["span", "110", "", "", ""],
  ["text", "400", "", "ระบุยี่ห้อ", ""],
  ["divend", "", "", "", ""],
  ["br", "", "", "", ""],
  ["br", "", "", "", ""],
  ["divbegin", "", "Retractor", "", ""],
  ["span", "110", "", "Retractor", ""],
  ["checkbox", "150", "", "Leylar", ""],
  ["checkbox", "150", "", "Halo", ""],
  ["checkbox", "", "", "Greenberg", ""],
  ["br", "", "", "", ""],
  ["span", "110", "", "", ""],
  ["text", "400", "", "", ""],
  ["divend", "", "", "", ""],
  ["br", "", "", "", ""],
  ["br", "", "", "", ""],
  ["divbegin", "", "CUSA", "", ""],
  ["span", "110", "", "CUSA", ""],
  ["checkbox", "150", "", "Excell", ""],
  ["checkbox", "150", "", "Soring", ""],
  ["checkbox", "", "", "Sonar", ""],
  ["br", "", "", "", ""],
  ["span", "110", "", "", ""],
  ["text", "400", "", "", ""],
  ["divend", "", "", "", ""],
  ["br", "", "", "", ""],
  ["br", "", "", "", ""],
  ["divbegin", "", "U/S", ""],
  ["span", "110", "", "U/S", ""],
  ["checkbox", "150", "", "Ultrasound", ""],
  ["checkbox", "150", "", "Doppler", ""],
  ["checkbox", "", "", "Duplex", ""],
  ["br", "", "", "", ""],
  ["span", "110", "", "", ""],
  ["text", "400", "", "", ""],
  ["divend", "", "", "", ""],
  ["br", "", "", "", ""],
  ["br", "", "", "", ""],
  ["divbegin", "", "Shunt", "", ""],
  ["span", "110", "", "Shunt", ""],
  ["br", "", "", "", ""],
  ["span", "10", "", "", ""],
  ["span", "30", "", "Pudenz", ""],
  ["span", "70", "", "", ""],
  ["radio", "150", "head", "หัว low", ""],
  ["radio", "150", "head", "หัว medium", ""],
  ["radio", "", "head", "หัว high", ""],
  ["br", "", "", "", ""],
  ["span", "110", "", "", ""],
  ["radio", "150", "peritoneum", "ท้อง low", ""],
  ["radio", "150", "peritoneum", "ท้อง medium", ""],
  ["radio", "", "peritoneum", "ท้อง high", ""],
  ["br", "", "", "", ""],
  ["span", "10", "", "", ""],
  ["span", "100", "", "Programmable", ""],
  ["radio", "150", "program", "Medtronic", ""],
  ["radio", "150", "program", "Codman", ""],
  ["radio", "", "program", "proGAV", ""],
  ["br", "", "", "", ""],
  ["span", "110", "", "", ""],
  ["text", "400", "", "", ""],
  ["divend", "", "", "", ""],
  ["br", "", "", "", ""],
  ["br", "", "", "", ""],
  ["divbegin", "", "เครื่องมือบริษัท", "", ""],
  ["span", "110", "", "เครื่องมือบริษัท", ""],
  ["span", "90", "", "เวลาส่งเครื่อง", ""],
  ["text", "200", "", "", ""],
  ["br", "", "", "", ""],
  ["span", "110", "", "", ""],
  ["text", "400", "", "ชื่อบริษัท ชื่อเครื่องมือ", ""],
  ["divend", "", "", "", ""],
  ["br", "", "", "", ""],
  ["br", "", "", "", ""],
  ["divbegin", "", "อุปกรณ์อื่นๆ", "", ""],
  ["span", "110", "", "อุปกรณ์อื่นๆ", ""],
  ["checkbox", "150", "", "MTEC skull", ""],
  ["checkbox", "", "", "cranioplastic Cement", ""],
  ["br", "", "", "", ""],
  ["span", "110", "", "", ""],
  ["text", "400", "", "", ""],
  ["divend", "", "", "", ""],
  ["br", "", "", "", ""],
  ["br", "", "", "", ""],
  ["divbegin", "", "Monitor", "", ""],
  ["span", "110", "", "Monitor", ""],
  ["checkbox", "150", "", "CN3", ""],
  ["checkbox", "150", "", "CN5", ""],
  ["checkbox", "", "", "CN6", ""],
  ["br", "", "", "", ""],
  ["span", "110", "", "", ""],
  ["checkbox", "150", "", "CN7", ""],
  ["checkbox", "150", "", "CN8", ""],
  ["checkbox", "", "", "CN9", ""],
  ["br", "", "", "", ""],
  ["span", "110", "", "", ""],
  ["checkbox", "150", "", "CN10", ""],
  ["checkbox", "150", "", "CN11", ""],
  ["checkbox", "", "", "CN12", ""],
  ["br", "", "", "", ""],
  ["span", "110", "", "", ""],
  ["checkbox", "150", "", "SSEP", ""],
  ["checkbox", "150", "", "EMG", ""],
  ["checkbox", "", "", "MEP", ""],
  ["br", "", "", "", ""],
  ["span", "110", "", "", ""],
  ["text", "400", "", "อื่นๆ", ""],
  ["divend", "", "", "", ""],
  ["br", "", "", "", ""],
  ["br", "", "", "", ""],
  ["divbegin", "", "Notice", "", ""],
  ["span", "110 floatleft", "", "Notice", ""],
  ["textarea", "400", "", "เครื่องมือพิเศษอื่นๆ", ""],
  ["divend", "", "", "", ""],
  ["br", "", "", "", ""],
  ["br", "", "", "", ""],
  ["divbegin", "", "", "", ""],
  ["span", "250", "", "", ""],
  ["span", "70", "", " Edited by ", ""],
  ["span", "", "", "", "editedby"],
  ["divend", "", "", "", ""],
  ["br", "", "", "", ""]
],

// ["type", "width", "name", "label", "id", "min", "max"]
LABSHEET = [
  ["spanInSpan", "", "", "วัน", "opdaylab"],
  ["spanInSpan", "100", "", "ที่ ", "opdatethlab"],
  ["br", "", "", "", ""],
  ["span", "70", "", "Surgeon", ""],
  ["span", "", "", "", "staffnamelab"],
  ["br", "", "", "", ""],
  ["span", "70", "", "ชื่อผู้ป่วย", ""],
  ["span", "", "", "", "patientnamelab"],
  ["br", "", "", "", ""],
  ["span", "70", "", "อายุ", ""],
  ["span", "", "", "", "agelab"],
  ["br", "", "", "", ""],
  ["span", "70", "", "HN", ""],
  ["span", "", "", "", "hnlab"],
  ["br", "", "", "", ""],
  // floatleft makes the subsequent text rows go downwards
  // instead of pushing previous rows upward
  ["span", "70 floatleft", "", "Diagnosis", ""],
  ["span", "200", "", "", "diagnosislab"],
  ["br", "", "", "", ""],
  ["span", "70 floatleft", "", "Operation", ""],
  ["span", "200", "", "", "treatmentlab"],
  ["br", "", "", "", ""],
  ["br", "", "", "", ""],
  ["text", "150", "", "Group ABO +- Rh", "gr"],
  ["br", "", "", "", ""],
  ["number", "150", "", "Packed Red Cells", "PRC", "0", "99"],
  ["br", "", "", "", ""],
  ["number", "150", "", "Fresh Frozen Plasma", "FFP", "0", "99"],
  ["br", "", "", "", ""],
  ["number", "150", "", "Whole Blood", "WB", "0", "99"],
  ["br", "", "", "", ""],
  ["number", "150", "", "Platelet Concentrate", "Plt", "0", "99"],
  ["br", "", "", "", ""],
  ["number", "150", "", "Cryoprecipitate", "Cryo", "0", "99"],
  ["br", "", "", "", ""],
  ["number", "150", "", "Factor IX", "IX", "0", "99"]
],

// [type, width, name, label, id, min, max]
PROFILESHEET = [
  ["number", "30", "admitted", "Admission", "", "0", "9"],
  ["div", "treatdiv", "", "", ""],
  ["hr", "outer", "", "", ""],
  ["button", "", "addOperation", "+", ""],
  ["divbegin", "", "operated", "Operation", "operated"],
  ["divend", "", "", "", ""],
  ["hr", "outer", "", "", ""],
  ["button", "", "addRadiosurgery", "+", ""],
  ["divbegin", "", "radiosurg", "Radiosurgery", "radiosurg"],
  ["divend", "", "", "", ""],
  ["hr", "outer", "", "", ""],
  ["button", "", "addEndovascular", "+", ""],
  ["divbegin", "", "endovasc", "Endovascular", "endovasc"],
  ["divend", "", "", "", ""],
  ["br", "", "", "", ""],
  ["hr", "outer", "", "", ""],
  ["checkbox", "100", "infection", "Infection", ""],
  ["checkbox", "100", "morbid", "Morbidity", ""],
  ["checkbox", "100", "dead", "Dead", ""]
],
OPERATION = [
  ["hr", "inner", "", "", ""],
  ["button", "", "delproc", "-", ""],
  ["text", "100", "opdateth", "", "opdateth"],
  ["br", "", "", "", ""],
  ["br", "", "", "", ""],
  ["br", "", "", "", ""],
  ["div", "textdiv", "", "", ""],
  ["br", "", "", "", ""],
  ["radio", "100", "doneby", "Staff", ""],
  ["radio", "100", "doneby", "Fellow", ""],
  ["radio", "100", "doneby", "Resident", ""],
  ["br", "", "", "", ""],
  ["radio", "100", "manner", "Elective", ""],
  ["radio", "100", "manner", "Emergency", ""],
  ["br", "", "", "", ""],
  ["radio", "100", "scale", "Major", ""],
  ["radio", "100", "scale", "Minor", ""],
  ["br", "", "", "", ""],
  ["radio", "100", "disease", "Brain Tumor", ""],
  ["radio", "100", "disease", "Trauma", ""],
  ["radio", "100", "disease", "Spine", ""],
  ["br", "", "", "", ""],
  ["radio", "100", "disease", "Brain Vascular", ""],
  ["radio", "100", "disease", "CSF related", ""],
  ["radio", "100", "disease", "etc", ""]
],
RADIOSURG = [
  ["hr", "inner", "", "", ""],
  ["button", "", "delproc", "-", ""],
  ["br", "", "", "", ""],
  ["br", "", "", "", ""],
  ["div", "textdiv", "", "", ""],
  ["br", "", "", "", ""],
  ["radio", "100", "doneby", "Staff Neuro", ""],
  ["radio", "100", "doneby", "Staff Radio", ""],
],
ENDOVASC = [
  ["hr", "inner", "", "", "", ""],
  ["button", "30 ", "delproc", "-", ""],
  ["text", "100", "opdateth", "", "opdateth"],
  ["br", "", "", "", ""],
  ["br", "", "", "", ""],
  ["br", "", "", "", ""],
  ["div", "textdiv", "", "", ""],
  ["br", "", "", "", ""],
  ["radio", "100", "doneby", "Staff Neuro", ""],
  ["radio", "100", "doneby", "Fellow Neuro", ""],
  ["radio", "100", "doneby", "Staff Radio", ""],
  ["br", "", "", "", ""],
  ["radio", "100", "manner", "Elective", ""],
  ["radio", "100", "manner", "Emergency", ""]
]
